#!/usr/bin/python3

import sys
import random 
 
f = open(sys.argv[1], "r")  
allText = f.read() 
Rep = allText.replace(sys.argv[2] , sys.argv[3])
print(Rep) 
#    print(random.choice(sys.argv[2])) 
#print (f.read())














