#!/usr/bin/python3

import sys

flag = False

n = int(sys.argv[1]) 

if n >1:
	for i in range(2,n):
		if (n % i) == 0:
			flag = True
			break
if flag:
	print(n, "is not prime fuck off")
else:
	print('yes thats it horaaaaa')
		







