#!/usr/bin/python3

n = input('please number:')
n = int(n)

def fac(n):
	out = 1
	for i in range(1,n+1):
		out = out * i
	return out
	
print(fac(n))		


##########

#!/usr/bin/python3

import sys

flag = False

n = int(sys.argv[1]) 

if n >1:
	for i in range(2,n):
		if (n % i) == 0:
			flag = True
			break
if flag:
	print(n, "is not prime fuck off")
else:
	print('yes thats it horaaaaa')
		
##########

#!/usr/bin/python3

import sys 

file_text = sys.argv[1]
let = sys.argv[2]
lete = sys.argv[3]
f = open(file_text, 'r')
allText = f.read()
#letters = r"\blet"
stand_word = allText.split()
possibilities = []
count = 0
for i in stand_word:
	if i.startswith(let) and i.endswith(lete):
		count += 1
		possibilities.append(i)
print(possibilities , count)

##########
#!/usr/bin/python3

import sys
import random 
 
f = open(sys.argv[1], "r")  
allText = f.read() 
Rep = allText.replace(sys.argv[2] , sys.argv[3])
print(Rep) 
# print(random.choice(sys.argv[2])) 
#print (f.read())

##########

#!/usr/bin/python3

import sys

n = int(sys.argv[1])
def fib(n):
	if n <= 1:
		return n
	else:
		return fib(n-1) + fib(n-2)
print(fib(n))


##########

#!/home/m76/bin/anaconda3/mlvenv/bin/python3


import sys
import random 
import time

#welcoming the user
name = input("What is your name? ")

print ("Hello, " + name, "Time to play hangman!")

#wait for 1 second
time.sleep(1)

print ("Start guessing...")
time.sleep(0.5)

#here we set the secret. You can select any word to play with. 
f = open(sys.argv[1], 'r')
allText = f.read()
stand_word = allText.split()
word = random.choice(stand_word)

#creates an variable with an empty value
guesses = ''

#determine the number of turns
turns = 10

# Create a while loop

#check if the turns are more than zero
while turns > 0:         

    # make a counter that starts with zero
    failed = 0             

    # for every character in secret_word    
    for char in word:      

    # see if the character is in the players guess
        if char in guesses:    
    
        # print then out the character
            print (char,end=""),    

        else:
    
        # if not found, print a dash
            print ("_",end=""),     
       
        # and increase the failed counter with one
            failed += 1    

    # if failed is equal to zero

    # print You Won
    if failed == 0:        
        print ("You won")
    # exit the script
        break            
    # ask the user go guess a character
    guess = input("guess a character:") 

    # set the players guess to guesses
    guesses += guess                    

    # if the guess is not found in the secret word
    if guess not in word:  
 
     # turns counter decreases with 1 (now 9)
        turns -= 1        
 
    # print wrong
        print ("Wrong")  
 
    # how many turns are left
        print ("You have", + turns, 'more guesses' )
 
    # if the turns are equal to zero
        if turns == 0:           
    
        # print "You Lose"
            print ("You Lose"  )

##########

#!/usr/bin/python3

#import time
#import random

#name = input("What is your name? ")

#print ("Hello, " + name, "Time to play rock,paper,scissor!")

#wait for 1 second
#time.sleep(1)

#print ("Start guessing...")
#time.sleep(0.5)

#geuss = input('guess: rock , paper , scissor:	')
#time.sleep(0.5)
#a = 'rock	'
#b = 'paper'
#c = 'scissor'
#f = [ a , b , c ];
#d = random.choice(f)
#       
#for geuss in f:       
#	if d == geuss:
#	if a == geuss:
#	tell again
#	if b == g
#	print (d,'won')
#else :
#	print (d,'you lose')   


import random

def get_computer_choice():
    return random.choice(["rock", "paper", "scissors"])

def determine_winner(player, computer):
    if player == computer:
        return "It's a tie!"
    elif (player == "rock" and computer == "scissors") or \
         (player == "scissors" and computer == "paper") or \
         (player == "paper" and computer == "rock"):
        return "You win!"
    else:
        return "Computer wins!"

def main():
    print("Welcome to Rock, Paper, Scissors!")
    while True:
        player_choice = input("Enter rock, paper, or scissors (or 'quit' to stop): ").lower()
        if player_choice == "quit":
            print("Thanks for playing! Goodbye!")
            break
        if player_choice not in ["rock", "paper", "scissors"]:
            print("Invalid choice. Please try again.")
            continue
        
        computer_choice = get_computer_choice()
        print(f"Computer chose: {computer_choice}")
        
        result = determine_winner(player_choice, computer_choice)
        print(result)
        print()

if __name__ == "__main__":
    main()



##########

#!/usr/bin/python3


import time
import sys

toolbar_width = 40

#setup toolbar
sys.stdout.write("[%s]" % (" " * toolbar_width))
sys.stdout.flush()
sys.stdout.write("\b" * (toolbar_width+1))  #return to start of line, after '['

for i in range(toolbar_width):
    time.sleep(0.1)  #do real work here
     #update the bar
    sys.stdout.write("█")
    sys.stdout.flush()

sys.stdout.write("]\n")
